name: Workflow Demo Dependent Jobs

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A job consists of"
      - run: echo "one or more steps"
      - run: echo "which run sequentially"
      - run: echo "within the same compute environment"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "multiple jobs can run in parallel"

  job-3:
    runs-on: ubuntu-slim
    needs: 
      - job-1
      - job-2
    steps:
      - run: echo "they can also depend on one another"

  job-4:
    runs-on: ubuntu-24.04
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "... to form a directed acyclic graph (DAG)"
